Search.appendIndex(
    [
                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController",
            "name": "CompromissoController",
            "summary": "Controlador\u0020da\u0020tabela\u0020e\u0020das\u0020rotas\u0020dos\u0020compromissos",
            "url": "classes/App-Http-Controllers-CompromissoController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Acadastrar\u0028\u0029",
            "name": "cadastrar",
            "summary": "Este\u0020\u00E9\u0020o\u0020POST\u0020do\u0020\/compromisso",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_cadastrar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Aatualizar\u0028\u0029",
            "name": "atualizar",
            "summary": "Este\u0020\u00E9\u0020o\u0020PUT\u0020do\u0020\/compromisso",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_atualizar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Adeletar\u0028\u0029",
            "name": "deletar",
            "summary": "Este\u0020\u00E9\u0020o\u0020DELETE\u0020do\u0020\/compromisso",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_deletar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Apesquisar\u0028\u0029",
            "name": "pesquisar",
            "summary": "Este\u0020\u00E9\u0020o\u0020GET\u0020do\u0020\/compromisso",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_pesquisar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Aformatar_data\u0028\u0029",
            "name": "formatar_data",
            "summary": "Usado\u0020para\u0020formatar\u0020a\u0020data\u0020em\u0020um\u0020modelo\u0020brasileiro\n\u0028n\u00E3o\u0020consegui\u0020usar\u0020YYYY\/MM\/DD,\u0020quando\u0020eu\u0020usava\u0020ficava\u0020YYYY\\\/MM\\\/DD\u0029",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_formatar_data"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\CompromissoController\u003A\u003Aformatar_hora\u0028\u0029",
            "name": "formatar_hora",
            "summary": "Usado\u0020para\u0020formatar\u0020a\u0020hora",
            "url": "classes/App-Http-Controllers-CompromissoController.html#method_formatar_hora"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ConsultorController",
            "name": "ConsultorController",
            "summary": "Controlador\u0020da\u0020tabela\u0020e\u0020das\u0020rotas\u0020dos\u0020consultores",
            "url": "classes/App-Http-Controllers-ConsultorController.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ConsultorController\u003A\u003Acadastrar\u0028\u0029",
            "name": "cadastrar",
            "summary": "Este\u0020\u00E9\u0020o\u0020POST\u0020do\u0020\/consultor",
            "url": "classes/App-Http-Controllers-ConsultorController.html#method_cadastrar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ConsultorController\u003A\u003Aatualizar\u0028\u0029",
            "name": "atualizar",
            "summary": "Este\u0020\u00E9\u0020o\u0020PUT\u0020do\u0020\/consultor",
            "url": "classes/App-Http-Controllers-ConsultorController.html#method_atualizar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ConsultorController\u003A\u003Adeletar\u0028\u0029",
            "name": "deletar",
            "summary": "Este\u0020\u00E9\u0020o\u0020DELETE\u0020do\u0020\/consultor",
            "url": "classes/App-Http-Controllers-ConsultorController.html#method_deletar"
        },                {
            "fqsen": "\\App\\Http\\Controllers\\ConsultorController\u003A\u003Apesquisar\u0028\u0029",
            "name": "pesquisar",
            "summary": "Este\u0020\u00E9\u0020o\u0020GET\u0020do\u0020\/consultor",
            "url": "classes/App-Http-Controllers-ConsultorController.html#method_pesquisar"
        },                {
            "fqsen": "\\App\\Models\\Compromisso",
            "name": "Compromisso",
            "summary": "",
            "url": "classes/App-Models-Compromisso.html"
        },                {
            "fqsen": "\\App\\Models\\Compromisso\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Compromisso.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Compromisso\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Compromisso.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Compromisso\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Compromisso.html#property_fillable"
        },                {
            "fqsen": "\\App\\Models\\Consultor",
            "name": "Consultor",
            "summary": "",
            "url": "classes/App-Models-Consultor.html"
        },                {
            "fqsen": "\\App\\Models\\Consultor\u003A\u003A\u0024table",
            "name": "table",
            "summary": "",
            "url": "classes/App-Models-Consultor.html#property_table"
        },                {
            "fqsen": "\\App\\Models\\Consultor\u003A\u003A\u0024timestamps",
            "name": "timestamps",
            "summary": "",
            "url": "classes/App-Models-Consultor.html#property_timestamps"
        },                {
            "fqsen": "\\App\\Models\\Consultor\u003A\u003A\u0024fillable",
            "name": "fillable",
            "summary": "",
            "url": "classes/App-Models-Consultor.html#property_fillable"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider",
            "name": "AppServiceProvider",
            "summary": "",
            "url": "classes/App-Providers-AppServiceProvider.html"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aregister\u0028\u0029",
            "name": "register",
            "summary": "Register\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_register"
        },                {
            "fqsen": "\\App\\Providers\\AppServiceProvider\u003A\u003Aboot\u0028\u0029",
            "name": "boot",
            "summary": "Bootstrap\u0020any\u0020application\u0020services.",
            "url": "classes/App-Providers-AppServiceProvider.html#method_boot"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory",
            "name": "UserFactory",
            "summary": "",
            "url": "classes/Database-Factories-UserFactory.html"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Adefinition\u0028\u0029",
            "name": "definition",
            "summary": "Define\u0020the\u0020model\u0027s\u0020default\u0020state.",
            "url": "classes/Database-Factories-UserFactory.html#method_definition"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003Aunverified\u0028\u0029",
            "name": "unverified",
            "summary": "Indicate\u0020that\u0020the\u0020model\u0027s\u0020email\u0020address\u0020should\u0020be\u0020unverified.",
            "url": "classes/Database-Factories-UserFactory.html#method_unverified"
        },                {
            "fqsen": "\\Database\\Factories\\UserFactory\u003A\u003A\u0024password",
            "name": "password",
            "summary": "The\u0020current\u0020password\u0020being\u0020used\u0020by\u0020the\u0020factory.",
            "url": "classes/Database-Factories-UserFactory.html#property_password"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder",
            "name": "DatabaseSeeder",
            "summary": "",
            "url": "classes/Database-Seeders-DatabaseSeeder.html"
        },                {
            "fqsen": "\\Database\\Seeders\\DatabaseSeeder\u003A\u003Arun\u0028\u0029",
            "name": "run",
            "summary": "Seed\u0020the\u0020application\u0027s\u0020database.",
            "url": "classes/Database-Seeders-DatabaseSeeder.html#method_run"
        },                {
            "fqsen": "\\LARAVEL_START",
            "name": "LARAVEL_START",
            "summary": "",
            "url": "namespaces/default.html#constant_LARAVEL_START"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Feature-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Feature\\ExampleTest\u003A\u003Atest_the_application_returns_a_successful_response\u0028\u0029",
            "name": "test_the_application_returns_a_successful_response",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Feature-ExampleTest.html#method_test_the_application_returns_a_successful_response"
        },                {
            "fqsen": "\\Tests\\TestCase",
            "name": "TestCase",
            "summary": "",
            "url": "classes/Tests-TestCase.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest",
            "name": "ExampleTest",
            "summary": "",
            "url": "classes/Tests-Unit-ExampleTest.html"
        },                {
            "fqsen": "\\Tests\\Unit\\ExampleTest\u003A\u003Atest_that_true_is_true\u0028\u0029",
            "name": "test_that_true_is_true",
            "summary": "A\u0020basic\u0020test\u0020example.",
            "url": "classes/Tests-Unit-ExampleTest.html#method_test_that_true_is_true"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\App\\Http\\Controllers",
            "name": "Controllers",
            "summary": "",
            "url": "namespaces/app-http-controllers.html"
        },                {
            "fqsen": "\\App\\Http",
            "name": "Http",
            "summary": "",
            "url": "namespaces/app-http.html"
        },                {
            "fqsen": "\\App",
            "name": "App",
            "summary": "",
            "url": "namespaces/app.html"
        },                {
            "fqsen": "\\App\\Models",
            "name": "Models",
            "summary": "",
            "url": "namespaces/app-models.html"
        },                {
            "fqsen": "\\App\\Providers",
            "name": "Providers",
            "summary": "",
            "url": "namespaces/app-providers.html"
        },                {
            "fqsen": "\\Database\\Factories",
            "name": "Factories",
            "summary": "",
            "url": "namespaces/database-factories.html"
        },                {
            "fqsen": "\\Database",
            "name": "Database",
            "summary": "",
            "url": "namespaces/database.html"
        },                {
            "fqsen": "\\Database\\Seeders",
            "name": "Seeders",
            "summary": "",
            "url": "namespaces/database-seeders.html"
        },                {
            "fqsen": "\\Tests\\Feature",
            "name": "Feature",
            "summary": "",
            "url": "namespaces/tests-feature.html"
        },                {
            "fqsen": "\\Tests",
            "name": "Tests",
            "summary": "",
            "url": "namespaces/tests.html"
        },                {
            "fqsen": "\\Tests\\Unit",
            "name": "Unit",
            "summary": "",
            "url": "namespaces/tests-unit.html"
        }            ]
);
